language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.2
  - 7.0
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit